
import React from 'react';
import { SkillCategory, Project, TimelineItem, Certification, ArsenalTool } from './types';

export const soundAssets: { [key: string]: string } = {
  type: 'data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAC+f//5//z/+/7/CgD6APj/7v/s//7/5P/t/+3/5f/p//L/7//u/+H/8v/j//L/9//1//L/6v/p//L/5P/q/+X/6f/u/+b/5v/l/+b/5//l/+f/5P/n/+T/5v/l/+f/5v/n/+X/6P/o/+n/6v/p/+n/6v/p/+r/6f/r/+r/7P/t/+//7v/w//P/9v/5//v//P/9//7/AQAEAAoADQARABUAGQAdACEAJQApAC0AMgA2ADsAQABFAEkATgBSAFYAWABbAF8AYwBnAGsAbwBzAHcAdgB6AHwAfgB/AIEAgwCDAIUAgwCEAIUAgwCDAIEAgAB+AHwAewB5AHcAeQBzAG8AawBnAGMAYQBfAFsAWQBVAFIAUABLAEYAQwA/ADsANgAyACwAJgAgABoAFAAOAAcAAgD7//b/8v/s/+b/4v/g/97/3f/b/9r/2v/d/9//4v/k/+f/6v/t//L/+v/+/wA=',
  click: 'data:audio/wav;base64,UklGRigAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAADWf/5//f/8//z/+/7/+//6//n/+f/5//r/+v/7//v/+///AQAEAAcACQALAA0ADwARABMAFQAXABkAGwAdAB8AIQAlACcAKQA=',
  submit: 'data:audio/wav;base64,UklGRlIAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQgAAAAgAACA/v/+AAMA/v/8/wAA/v8AAP7//P8A/v8AAP7/+/7/AwD+/v3/+/7/BgD9//z/BgD9//v+AAEABP/9/v8AAQAD//r/+/7/9v/w/+f/4//h/+H/5f/q/+z/7//x//T/+v8AAP//AQAEAAYACQALAA4AEQAUABcAGgAdACAAMQA0ADYAOQA7ADwAPgA/AEAAQQBCAEMARABFAEYARwBIAEkASgBLAEwATQBOAE8AUABRAFIAUwBUAFUAVgBXAFgAWQBaAFsAXABdAF4AXwBgAGEAYgBjAGQAZQBmAGc=',
};

export const ALL_SKILLS: SkillCategory[] = [
    { title: "OWASP Top 10", skills: [{ name: "A01 – Broken Access Control", details: "IDOR, Privilege Escalation" }, { name: "A02 – Cryptographic Failures", details: "Weak SSL/TLS, Insecure Hash, Hardcoded Secrets" }, { name: "A03 – Injection", details: "SQLi, Command Injection, NoSQL Injection" }, { name: "A04 – Insecure Design", details: "Logic Flaws, Business Logic Abuse" }, { name: "A05 – Security Misconfiguration", details: "Default creds, Open admin panels, Misconfigured CORS" }, { name: "A06 – Vulnerable & Outdated Components", details: "Old libs, Unpatched CVEs" }, { name: "A07 – Identification & Authentication Failures", details: "Broken JWT, Weak session, MFA bypass" }, { name: "A08 – Software & Data Integrity Failures", details: "Insecure deserialization, Supply chain attack" }, { name: "A09 – Security Logging & Monitoring Failures", details: "Lack of alerts, Undetected brute-force" }, { name: "A10 – Server-Side Request Forgery (SSRF)", details: "Pivoting, Cloud metadata leaks" }] },
    { title: "Web Exploitation", skills: [{ name: "Cross-Site Scripting (XSS)", details: "Stored/Reflected/DOM" }, { name: "Server-Side Template Injection (SSTI)", details: "" }, { name: "File Inclusion", details: "LFI/RFI, File Upload Bypass" }, { name: "Cross-Site Request Forgery (CSRF)", details: "" }, { name: "Open Redirect", details: "" }] },
    { title: "Active Directory Attacks", skills: [{ name: "Kerberos Attacks", details: "Kerberoasting, AS-REP Roasting" }, { name: "Credential Theft", details: "Pass-the-Hash, DCSync" }, { name: "Persistence & Privilege", details: "Golden Ticket, ADCS abuse" }] },
    { title: "Network Attacks", skills: [{ name: "Service Enumeration", details: "SMB/LDAP/FTP enum" }, { name: "Spoofing & Interception", details: "MITM, ARP Spoofing" }, { name: "Covert Channels", details: "DNS Tunneling, Reverse Shells with Netcat" }] },
    { title: "Defensive Security & SIEM", skills: [{ name: "SOC Operations", details: "Tier 1 analysis, Incident triage" }, { name: "Wazuh", details: "Endpoint monitoring, HIDS deployment" }, { name: "ELK Stack", details: "Log aggregation, Elasticsearch, Kibana" }, { name: "Suricata / Snort", details: "NIDS/NIPS rule development" }] },
    { title: "Infrastructure & Lab Management", skills: [{ name: "Windows Server", details: "Domain Controller, GPO, DNS" }, { name: "Active Directory", details: "Forest/Domain setup, user management" }, { name: "CentOS / Linux", details: "System hardening, service configuration" }, { name: "Virtualization", details: "VMware, VirtualBox lab environments" }] },
    { title: "Programming & DevOps", skills: [{ name: "Python", details: "Scripting, Automation, Security Tool Dev" }, { name: "C / C++", details: "System-level programming, Exploit Dev" }, { name: "Java", details: "Enterprise Application Security" }, { name: "PHP", details: "Backend Development, Reverse Shells" }, { name: "HTML / CSS / JS", details: "Frontend, DOM XSS Analysis" }, { name: "Docker", details: "Containerization, Secure Environment Setup" }] }
];

export const PROJECTS_DATA: Project[] = [
    { id: 1, type: "WEB_APP", title: "E-Commerce Platform Assessment", description: "Comprehensive pentest focusing on OWASP Top 10 and business logic flaws.", findings: [{ severity: "CRITICAL", text: "SQL Injection in API." }, { severity: "HIGH", text: "Broken Access Control (ATO)." }, { severity: "MED", text: "Stored XSS in review section." }], objective: "Identify and validate critical vulnerabilities in a customer-facing e-commerce application before its major holiday sales launch, focusing on payment processing and user data integrity.", attackChain: ["1. Mapped API endpoints and identified a legacy endpoint vulnerable to SQL Injection.", "2. Exploited SQLi to dump user credential hashes and sensitive order information.", "3. Discovered an Insecure Direct Object Reference (IDOR) in the user profile endpoint, allowing unauthorized access to other users' accounts by iterating identifiers.", "4. Successfully performed an Account Takeover (ATO) of a test administrator account.", "5. Injected a stored XSS payload into the product review field, demonstrating the ability to capture session cookies from other users, including administrators."], businessImpact: "A successful breach could have led to a massive customer data leak, fraudulent transactions, and significant reputational damage, resulting in millions in potential losses and regulatory fines.", status: "All critical and high-risk vulnerabilities were patched by the client's development team prior to the sales event. [REMEDIATED]", toolsUsed: ["Burp Suite", "SQLMap", "Nmap"] },
    { id: 2, type: "INTERNAL_NETWORK", title: "Corporate AD Pentest", description: "Assumed-breach scenario testing internal defenses and lateral movement paths.", findings: [{ severity: "CRITICAL", text: "Domain Admin via Kerberoasting." }, { severity: "HIGH", text: "Unpatched legacy system foothold." }, { severity: "HIGH", text: "LLMNR Poisoning for cred capture." }], objective: "Simulate a low-privilege attacker within the corporate network and assess the pathways to achieve Domain Administrator privileges, identifying weaknesses in Active Directory configuration and segmentation.", attackChain: ["1. Established initial foothold on an unpatched Windows 7 machine in the marketing department VLAN.", "2. Used Responder to perform LLMNR/NBT-NS poisoning, capturing NTLMv2 hashes from network traffic.", "3. Performed a Kerberoasting attack to extract service account hashes for services with weak SPNs.", "4. Cracked a weak service account password offline using Hashcat.", "5. Leveraged the compromised service account's privileges to perform a DCSync attack, extracting all domain credential hashes, including the krbtgt account.", "6. Forged a Golden Ticket to gain persistent, full Domain Administrator access."], businessImpact: "A complete compromise of the Active Directory would grant an attacker full control over the entire corporate network, including all user accounts, servers, and sensitive data, leading to a catastrophic security incident.", status: "Remediation guidance focused on network segmentation, patching policies, disabling legacy protocols, and implementing strong password policies for service accounts. [REMEDIATED]", toolsUsed: ["Responder", "Hashcat", "Impacket", "Metasploit"] },
    { id: 6, type: "INTERNAL_NETWORK", title: "Internal Network & AD Lab Buildout", description: "Constructed a multi-vlan enterprise environment for pentesting practice.", findings: [{ severity: "INFO", text: "Created realistic user profiles and groups." }, { severity: "INFO", text: "Deployed intentionally vulnerable services." }, { severity: "INFO", text: "Configured AD with common misconfigurations." }], objective: "Build a fully functional and realistic Windows Server Active Directory lab environment from scratch to practice and demonstrate various TTPs for internal network penetration tests.", attackChain: ["1. Deployed Windows Server as a Domain Controller, configuring DNS, DHCP, and Certificate Services.", "2. Created multiple OUs, users, and groups to simulate a corporate structure.", "3. Joined Windows and Linux client machines to the domain across different VLANs.", "4. Intentionally introduced vulnerabilities such as weak passwords, disabled security features, and misconfigured service permissions to create a target-rich environment.", "5. Validated the lab by successfully executing attacks like Kerberoasting and Pass-the-Hash from a Kali Linux attacker machine."], businessImpact: "This project provides a critical, hands-on training platform for honing advanced Active Directory attack and defense skills in a safe and controlled environment, directly translating to effectiveness in real-world engagements.", status: "Lab is operational and actively used for skill development. [ACTIVE]", toolsUsed: ["Windows Server", "VMware", "CentOS", "Kali Linux"] },
    { id: 7, type: "SIEM_DEPLOYMENT", title: "SOC Operations & SIEM Deployment", description: "Built and managed a security monitoring stack using open-source tools.", findings: [{ severity: "HIGH", text: "Developed rules to detect web attacks." }, { severity: "MED", text: "Configured endpoint monitoring for malware." }, { severity: "INFO", text: "Created dashboards for threat visualization." }], objective: "Deploy and configure a complete Security Information and Event Management (SIEM) solution to provide monitoring, threat detection, and alerting for a simulated corporate network.", attackChain: ["1. Deployed the ELK Stack (Elasticsearch, Logstash, Kibana) for centralized log aggregation and analysis.", "2. Installed and configured Wazuh agents on Windows and Linux endpoints to collect security events, file integrity data, and vulnerability information.", "3. Integrated Suricata NIDS to monitor network traffic for malicious signatures and anomalies.", "4. Wrote custom correlation rules in Wazuh and ElastAlert to detect specific attack patterns, such as brute-force attempts and suspicious PowerShell execution.", "5. Built custom Kibana dashboards to visualize security events, track incident response metrics, and provide high-level reporting for management."], businessImpact: "Demonstrates a comprehensive understanding of defensive security operations, from data collection and analysis to threat detection and visualization, providing the foundation for a robust Security Operations Center (SOC).", status: "System deployed and functional in a lab environment. [COMPLETE]", toolsUsed: ["Wazuh", "ELK Stack", "Suricata", "ElastAlert"] },
    { id: 8, type: "IOT_HEALTH_AI", title: "AI-Powered IoT Health Monitoring System Build", description: "Engineered a full-stack IoT health monitoring PoC, leveraging an Arduino Mega 2560 for data acquisition, a Python Flask backend for data processing, and an integrated AI model for real-time anomaly detection.", findings: [{ severity: "INFO", text: "Arduino firmware for sensor data collection." }, { severity: "INFO", text: "Python Flask API for data processing." }, { severity: "INFO", text: "Integrated AI model for anomaly detection." }], objective: "To build an end-to-end IoT system capable of collecting real-time health metrics, processing them through a cloud-based AI, and alerting on potential health issues, demonstrating skills in hardware integration, backend development, and applied machine learning.", attackChain: ["1. Developed C++ firmware for the Arduino Mega 2560 to interface with health sensors (e.g., pulse, temperature).", "2. Built a RESTful API using Python Flask to serve as the central backend, handling data ingestion and user management.", "3. Trained and integrated a TensorFlow/Keras model into the Flask application to analyze sensor data for anomalies.", "4. Established a secure communication channel using MQTT for efficient data transmission from the Arduino to the server.", "5. Designed a simple web-based dashboard to visualize live health data and AI-generated alerts."], businessImpact: "This project demonstrates the ability to architect and build a secure, scalable, and intelligent IoT solution from scratch, showcasing skills in embedded systems, cloud development, and applied AI.", status: "Proof-of-concept system built and functional. [POC_COMPLETE]", toolsUsed: ["Arduino Mega 2560", "Python (Flask)", "TensorFlow/Keras", "MQTT", "C++"] },
    { id: 9, type: "AD_SECURITY", title: "Active Directory Attack Simulator", description: "Developed a Python-based tool to simulate common Active Directory attacks for blue team training and control validation.", findings: [{ severity: "INFO", text: "Implemented Kerberoasting simulation." }, { severity: "INFO", text: "Added password spray module." }, { severity: "INFO", text: "Designed for easy integration into test pipelines." }], objective: "To create a lightweight, scriptable tool that allows security teams to test their detection and response capabilities against known TTPs like Kerberoasting and password spraying.", attackChain: ["1. Designed the tool's architecture, focusing on modularity for different attack techniques.", "2. Implemented a Kerberoasting module using the Impacket library to request service tickets.", "3. Added a password spraying module that safely tests common passwords against a list of users.", "4. Integrated LDAP3 for efficient and safe querying of the Active Directory environment.", "5. Packaged the tool for easy deployment in isolated lab environments."], businessImpact: "Empowers blue teams to proactively validate SIEM rules, EDR alerts, and incident response playbooks in a controlled manner, leading to a hardened Active Directory environment.", status: "[COMPLETE]", toolsUsed: ["Python", "Impacket", "LDAP3"], githubLink: "https://github.com/1yn3r/ad-attack-sim" },
    { id: 10, type: "HARDWARE_INTEGRATION", title: "PC Performance Monitor on Arduino", description: "Created a system to display real-time PC performance statistics (CPU/GPU temp, usage) on an external LCD screen connected to an Arduino.", findings: [{ severity: "INFO", text: "Firmware for real-time data display." }, { severity: "INFO", text: "Python script for data collection." }, { severity: "INFO", text: "Established reliable serial communication." }], objective: "To design and build a functional hardware solution for at-a-glance PC monitoring, combining hardware programming with a lightweight desktop software component.", attackChain: ["1. Wrote C++ code for an Arduino to initialize an I2C LCD and parse incoming serial data.", "2. Developed a Python script on the host PC to gather system metrics using libraries like `psutil` and `gputil`.", "3. Formatted the collected data into a concise string and transmitted it over the USB serial port.", "4. Implemented error handling to manage connection interruptions and ensure data integrity.", "5. Designed and 3D-printed a custom enclosure for the Arduino and LCD screen for a clean setup."], businessImpact: "Demonstrates practical skills in hardware integration, embedded C++ programming, serial communication, and desktop scripting, showcasing the ability to bridge software and physical hardware.", status: "[COMPLETE]", toolsUsed: ["Arduino", "C++", "Python", "Serial I/O"], githubLink: "https://github.com/1yn3r/Arduino-Display-PC" },
    { id: 11, type: "TOOL_CONTRIBUTION", title: "Cameradar - RTSP Stream Scanner", description: "Contributed to 'Cameradar', an open-source tool written in Go, designed to scan for and access unprotected RTSP video streams on network devices.", findings: [{ severity: "INFO", text: "Improved scanning efficiency." }, { severity: "INFO", text: "Added new device signatures." }, { severity: "INFO", text: "Fixed bugs in network protocol handling." }], objective: "To enhance the tool's capabilities and deepen my understanding of network scanning techniques, IoT device security, and the Go programming language.", attackChain: ["1. Analyzed the existing codebase to identify performance bottlenecks in the network scanning module.", "2. Refactored parts of the RTSP handshake logic to handle edge cases and reduce timeouts.", "3. Researched and added signatures for several new models of IP cameras, expanding the tool's detection capabilities.", "4. Submitted pull requests with detailed explanations and test cases, collaborating with the project maintainer."], businessImpact: "Participation in widely-used open-source security tools showcases a commitment to the community, collaborative development skills, and a deeper understanding of real-world device vulnerabilities.", status: "[CONTRIBUTION]", toolsUsed: ["Go", "RTSP Protocol", "Git", "Nmap"], githubLink: "https://github.com/1yn3r/cameradar" }
];

export const TIMELINE_DATA: TimelineItem[] = [
    { year: "2021-2022", title: "Endpoint Security Engineer, HPT", description: "Deployed and managed enterprise endpoint security solutions, specializing in the Kaspersky Security Center suite. Responsible for policy configuration, incident response, and system hardening for large-scale client networks." },
    { year: "2022", title: "Pivot to Offensive Security", description: "Began a dedicated self-study curriculum focused on penetration testing methodologies, leveraging platforms like TryHackMe and Hack The Box to build foundational offensive skills." },
    { year: "2023", title: "Homelab & Project Development", description: "Designed and built a multi-VLAN virtual lab environment to practice Active Directory attacks, SIEM deployment, and network segmentation. Began developing custom security tools." },
    { year: "2024", title: "Advanced Skill Acquisition", description: "Focused on advanced penetration testing techniques, including web application exploits (OWASP Top 10), advanced AD attacks, and completing comprehensive learning paths like the Jr Penetration Tester certification track." },
    { year: "2025", title: "Penetration Tester Intern, HALI CARE", description: "Completed a 3-month internship (May-Aug) focused on enterprise penetration testing. Conducted vulnerability assessments, manual web application testing, and contributed to client-facing reports for corporate systems." }
];

export const CERTIFICATIONS_DATA: Certification[] = [
    { name: "Jr Penetration Tester", issuer: "TryHackMe", verifyLink: "https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-47WH17KJWN.pdf", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path><circle cx="12" cy="12" r="3"></circle><path d="M12 15v3"></path></svg> },
    { name: "Offensive Pentesting", issuer: "TryHackMe", verifyLink: "https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-C2OWVYVHSN.pdf", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path><line x1="12" y1="8" x2="12" y2="16"></line><line x1="10" y1="10" x2="14" y2="10"></line></svg> },
    { name: "Cyber Defense", issuer: "TryHackMe", verifyLink: "https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-YMZOCUBNHI.pdf", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path><path d="M7 13h10"></path><path d="M7 9h5"></path><path d="M14 9h3"></path><path d="M7 17h3"></path><path d="M12 17h5"></path></svg> },
    { name: "Pre Security", issuer: "TryHackMe", verifyLink: "https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-H49SGLKF8O.pdf", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path><circle cx="11" cy="11" r="3"></circle><line x1="13" y1="13" x2="15" y2="15"></line></svg> },
    { name: "Complete Beginner", issuer: "TryHackMe", verifyLink: "https://tryhackme-certificates.s3-eu-west-1.amazonaws.com/THM-QJTIJVJ1OV.pdf", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path><circle cx="12" cy="12" r="1"></circle></svg> },
];

export const ARSENAL_TOOLS: ArsenalTool[] = [
    { name: "Burp Suite", description: "The premier toolkit for web application penetration testing. Used daily for intercepting, manipulating, and analyzing web traffic.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="currentColor"><path d="M21.92,5.54A1,1,0,0,0,21,5H15.45a1,1,0,0,0-.86.49L12,9.62,9.41,5.49A1,1,0,0,0,8.55,5H3a1,1,0,0,0-.92.69,1,1,0,0,0,.2,1l7.29,11.12a1,1,0,0,0,1.62.06l7.5-11A1,1,0,0,0,21.92,5.54Z"/></svg> },
    { name: "OWASP ZAP", description: "An open-source web application security scanner. Essential for finding vulnerabilities during development and testing.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M12 2 L12 6 M12 18 L12 22 M6 12 L2 12 M22 12 L18 12 M16.95 7.05 L19.78 4.22 M4.22 19.78 L7.05 16.95 M7.05 7.05 L4.22 4.22 M19.78 19.78 L16.95 16.95 M12 12 L9.5 5.5 L14.5 5.5 Z M12 12 L18.5 14.5 L18.5 9.5 Z M12 12 L5.5 14.5 L5.5 9.5 Z M12 12 L9.5 18.5 L14.5 18.5 Z" strokeLinejoin="round" strokeLinecap="round" /></svg> },
    { name: "Nmap", description: "Network Mapper. The foundational tool for network discovery, port scanning, and service enumeration.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="m14.31 8.69-6 6"/><path d="m8.69 8.69 6 6"/></svg> },
    { name: "Metasploit", description: "The world's leading exploitation framework. Used for developing, testing, and executing exploit code against remote targets.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="currentColor"><path d="M12,2A10,10,0,0,0,2,12A10,10,0,0,0,12,22A10,10,0,0,0,22,12A10,10,0,0,0,12,2M12,4L18,7.5V16.5L12,20L6,16.5V7.5L12,4M12,11.1L15,9.5V11L12,12.5L9,11V9.5L12,11.1M11,13H13V18H11V13Z"/></svg> },
    { name: "Wireshark", description: "The industry-standard network protocol analyzer. Essential for deep packet inspection and network troubleshooting.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="currentColor"><path d="M12,2C6.48,2,2,6.48,2,12s4.48,10,10,10,10-4.48,10-10S17.52,2,12,2z M12,20c-4.41,0-8-3.59-8-8s3.59-8,8-8 s8,3.59,8,8S16.41,20,12,20z M11.5,15.5l-4-4l1.41-1.41L11.5,12.67l4.59-4.59L17.5,9.5l-6,6z"/></svg> },
    { name: "Hashcat", description: "The world's fastest and most advanced password recovery utility. Used for offline cracking of captured hashes.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="currentColor"><path d="M12,2C6.48,2,2,6.48,2,12s4.48,10,10,10s10-4.48,10-10S17.52,2,12,2z M12,20c-4.41,0-8-3.59-8-8s3.59-8,8-8 s8,3.59,8,8S16.41,20,12,20z M12,6c-3.31,0-6,2.69-6,6s2.69,6,6,6s6-2.69,6-6S15.31,6,12,6z M12,16c-2.21,0-4-1.79-4-4 s1.79-4,4-4s4,1.79,4,4S14.21,16,12,16z"/></svg> },
    { name: "Impacket", description: "A collection of Python classes for working with network protocols. Indispensable for Active Directory and Windows network attacks.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m10 17 5-5-5-5"/><path d="m17 17-5-5 5-5"/></svg> },
    { name: "SQLMap", description: "Automates the process of detecting and exploiting SQL injection flaws and taking over database servers.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><ellipse cx="12" cy="5" rx="9" ry="3"/><path d="M21 12c0 1.66-4 3-9 3s-9-1.34-9-3"/><path d="M3 5v14c0 1.66 4 3 9 3s9-1.34 9-3V5"/></svg> },
    { name: "Hydra", description: "A fast and flexible network logon cracker which supports numerous protocols to attack.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19.25 12.25a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Z"/><path d="M8.75 12.25a2.25 2.25 0 1 1-4.5 0 2.25 2.25 0 0 1 4.5 0Z"/><path d="M14 18.25s-1.5-2-4-2-4 2-4 2"/><path d="M12 2.75a4 4 0 0 0-4 4v1.5a2.5 2.5 0 0 0-2.5 2.5v0a2.5 2.5 0 0 0 2.5 2.5v1.5a4 4 0 0 0 4 4h0a4 4 0 0 0 4-4v-1.5a2.5 2.5 0 0 0 2.5-2.5v0a2.5 2.5 0 0 0-2.5-2.5v-1.5a4 4 0 0 0-4-4h0Z"/></svg> },
    { name: "John the Ripper", description: "A classic and powerful password cracker. Supports hundreds of hash and cipher types.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/><path d="M16 8h-2a2 2 0 1 0 0-4h2"/><path d="M8 12H6a2 2 0 1 0 0 4h2"/><path d="M12 12h2a2 2 0 1 1 0 4h-2"/></svg> },
    { name: "Aircrack-ng", description: "A complete suite of tools to assess Wi-Fi network security. Used for monitoring, attacking, testing, and cracking.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M5 12.55a8 8 0 0 1 14.08 0"/><path d="M1.42 9a16 16 0 0 1 21.16 0"/><path d="M8.53 16a4 4 0 0 1 6.95 0"/><line x1="12" x2="12" y1="20" y2="22"/></svg> },
    { name: "Dir Fuzzers", description: "Tools like Dirsearch & Gobuster are essential for discovering hidden directories and files on web servers.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/><line x1="9" x2="9" y1="14" y2="14"/><line x1="15" x2="15" y1="14" y2="14"/></svg> },
    { name: "SpiderFoot", description: "An open-source intelligence (OSINT) automation tool. Gathers intelligence about a target from a vast number of data sources.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 6.265v-3.265"/><path d="m12.93 4.07-1.86-.001"/><path d="M17.845 7.625 15.5 6.5"/><path d="m18.915 11.07-2.345-1.5"/><path d="M17.845 14.375 15.5 15.5"/><path d="m12.93 17.93-.001-1.86"/><path d="M12 15.735v3.265"/><path d="m11.07 17.93.001-1.86"/><path d="m6.155 14.375 2.345 1.125"/><path d="m5.085 11.07 2.345 1.5"/><path d="m6.155 7.625 2.345-1.125"/><path d="m11.07 4.07 1.86-.001"/><circle cx="12" cy="11" r="5"/><circle cx="12" cy="11" r="1"/></svg> },
    { name: "Covenant", description: "An open-source .NET command and control framework. Used for post-exploitation and red team operations.", icon: (props) => <svg {...props} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg> },
];

export const HIGHLIGHTED_PROJECTS: Project[] = PROJECTS_DATA.filter(p => [1, 2, 7].includes(p.id));
